from .usuario import Usuario
from .cliente import Cliente
from .empleado import Empleado
from .proveedor import Proveedor
from .producto import Producto
from .inventario import Inventario
from .factura import Factura
from .detalleFactura import DetalleFactura
from .compraProveedor import CompraProveedor
from .detalleCompra import DetalleCompra
from .rol import Rol
from .sucursal import Sucursal
from .tipoProducto import TipoProducto
